import logging
from collections import defaultdict
from math import copysign

from odoo import _, fields, models

_logger = logging.getLogger(__name__)


class AccountMoveLine(models.Model):
    _inherit = "account.move.line"

    # Adds a direct link to the off-balance and on-balance associated lines
    on_balance_line_ids = fields.Many2many(
        "account.move.line",
        "account_move_line_off_balance_rel",
        "off_balance_line_id",
        "on_balance_line_id",
        string="On-Balance Lines",
        help="Lines generated on-balance from this off-balance line.",
        copy=False,
    )
    off_balance_line_ids = fields.Many2many(
        "account.move.line",
        "account_move_line_off_balance_rel",
        "on_balance_line_id",
        "off_balance_line_id",
        string="Off-Balance Line",
        help="Link to the off-balance lines associated with this on-balance line.",
        copy=False,
    )
    is_off_balance_generated = fields.Boolean(
        help="Technical field used to identify lines generated by the off-balance "
        "reconciliation process.",
    )

    def _search(self, domain, offset=0, limit=None, order=None, access_rights_uid=None):
        if self.env.context.get("filter_off_balance"):
            domain.append(("account_id.is_off_balance", "=", False))
        return super()._search(domain, offset, limit, order, access_rights_uid)

    def _reconcile_post_hook(self, data):
        super()._reconcile_post_hook(data)
        income_off_balance = self.move_id.line_ids.filtered(
            lambda move_line: move_line.account_id.is_off_balance
            and move_line.company_id.off_balance_asset_account_id
        )
        if income_off_balance:
            self._register_off_balance_income()

    def remove_move_reconcile(self):
        self.filtered("is_off_balance_generated").with_context(
            force_delete=True
        ).unlink()
        return super(AccountMoveLine, self.exists()).remove_move_reconcile()

    def _register_off_balance_income(self):
        """
        When an income is reconciled, we look if it was linked to a donation invoiced
        on the off-balance account. If so, we create the corresponding lines on the
        on-balance account.

        We cover the following scenarios:
        1. The income is directly reconciled with an invoice
        2. The income is reconciled with a debit order connected with the invoice
           a. Full reconciliation
           b. Partial reconciliation

        :param self: The reconciled lines
        :return: True if lines were created, False otherwise
        """
        # Step 1: Get income move lines
        income_move_lines = self._get_income_move_lines()
        if not income_move_lines:
            _logger.debug("No income move lines found for off-balance registration")
            return False

        # Step 2: Get related invoice lines
        invoice_lines = self._get_related_invoice_lines()

        # Step 3: Validate off-balance lines exist
        off_balance_lines = invoice_lines.filtered("account_id.is_off_balance")
        if not off_balance_lines:
            _logger.debug("No off-balance credit lines found")
            return False

        # Step 4: Build on-balance amounts by account and product
        onbalance_amounts_by_account = self._build_onbalance_amounts(
            invoice_lines, income_move_lines
        )

        if not onbalance_amounts_by_account:
            _logger.debug("No on-balance amounts to process")
            return False

        # Step 5: Create on-balance move lines
        income_entry = income_move_lines.move_id[0]
        self._create_onbalance_move_lines(
            onbalance_amounts_by_account,
            income_entry,
        )

        amount_distributed = sum(
            income_entry.line_ids.filtered(
                lambda mvl: mvl.is_off_balance_generated
                and mvl.account_id.is_off_balance
            ).mapped("balance")
        )
        _logger.info(
            "Created off-balance adjustment for move %s, amount: %s",
            income_entry.name,
            amount_distributed,
        )
        return True

    def _get_income_move_lines(self):
        """
        Extract income move lines: those with asset accounts credited
        linked to the reconciled receivable lines.
        (should not be an outstanding payment)

        :return: Recordset of income move lines
        """
        return self.move_id.line_ids.filtered(
            lambda line: line.move_type == "entry"
            and line.account_internal_group == "asset"
            and line.credit
            and not line.payment_id
            and line.journal_id.type in ("bank", "cash")
        )

    def _get_related_invoice_lines(self):
        """
        Get invoice lines related to the reconciled lines.

        Handles two scenarios:
        - Direct reconciliation with invoices
        - Reconciliation through debit orders

        :return: Recordset of invoice lines sorted by invoice total amount
                 (so that invoices have a chance to be fully processed
                 if the total amount is not enough)
        """
        invoices = self.filtered(
            lambda mvl: mvl.move_type in ("out_invoice", "out_refund")
        ).move_id
        if invoices:
            # Scenario 1: Direct reconciliation with invoice
            return invoices.sorted("amount_total").mapped("invoice_line_ids")
        else:
            # Scenario 2: Reconciliation through debit order
            # Fetch all reconciled lines and filter invoices
            all_reconciled_lines = (
                self.move_id.line_ids.full_reconcile_id.reconciled_line_ids
            )
            return (
                all_reconciled_lines.move_id.filtered(
                    lambda m: m.move_type in ("out_invoice", "out_refund")
                )
                .sorted("amount_total")
                .mapped("invoice_line_ids")
            )

    def _build_onbalance_amounts(self, invoice_lines, income_move_lines):
        """
        Build a dictionary of on-balance amounts grouped by invoice line.

        The amounts are computed in both company currency and the invoice currency.

        :param invoice_lines: Invoice lines to process
        :param income_move_lines: Income move lines
        :return: Dictionary of (amount, amount_currency) by invoice line.
        """
        onbalance_amounts_by_line = {}
        total_income = abs(sum(income_move_lines.mapped("balance")))
        total_income_currency = abs(sum(income_move_lines.mapped("amount_currency")))
        total_already_distributed = abs(
            sum(invoice_lines.mapped("on_balance_line_ids.balance"))
        )
        total_already_distributed_currency = abs(
            sum(invoice_lines.mapped("on_balance_line_ids.amount_currency"))
        )
        available_income = total_income - total_already_distributed
        available_income_currency = (
            total_income_currency - total_already_distributed_currency
        )

        # Process invoice lines with on-balance accounts
        # We group by invoice to compute the distribution ratio once per invoice
        # This ensures that all lines of the same invoice get the same ratio
        # based on the available income at the time we start processing that invoice.
        invoices = invoice_lines.move_id.sorted("amount_total")

        for invoice in invoices:
            if invoice.currency_id.is_zero(available_income):
                break

            # Compute ratio based on the available income for this invoice
            ratio = invoice._compute_invoice_distribution_ratio(available_income)

            # Filter lines for this invoice that need processing
            lines = invoice_lines.filtered(
                lambda line, iv=invoice: line.move_id == iv
                and line.account_id.on_balance_account_id
            )

            for invoice_line in lines:
                # Keep track of amounts in company currency and line currency
                remaining_amount = invoice_line.balance
                remaining_amount_currency = invoice_line.amount_currency
                if invoice_line.on_balance_line_ids:
                    # When an on-balance line is linked to multiple invoice lines
                    # (e.g. same product), we must split its amount
                    # to avoid double counting the distributed amount.
                    already_distributed_amount = 0.0
                    already_distributed_amount_currency = 0.0
                    for line in invoice_line.on_balance_line_ids.filtered(
                        "off_balance_line_ids"
                    ):
                        count = len(
                            line.off_balance_line_ids.filtered(
                                lambda line, ivl=invoice_line: line.account_id
                                == ivl.account_id
                            )
                        )
                        already_distributed_amount += line.balance / count
                        already_distributed_amount_currency += (
                            line.amount_currency / count
                        )

                    already_distributed = copysign(
                        already_distributed_amount,
                        remaining_amount,
                    )
                    already_distributed_currency = copysign(
                        already_distributed_amount_currency,
                        remaining_amount_currency,
                    )
                    remaining_amount -= already_distributed
                    remaining_amount_currency -= already_distributed_currency
                if invoice_line.currency_id.is_zero(remaining_amount):
                    continue

                # Use the invoice-level ratio
                def get_dist_amount(amount_to_distribute, limit):
                    return copysign(
                        min(abs(amount_to_distribute), limit),
                        amount_to_distribute,
                    )

                distributed_amount = get_dist_amount(
                    remaining_amount * ratio, available_income
                )
                distributed_amount_currency = get_dist_amount(
                    remaining_amount_currency * ratio,
                    available_income_currency,
                )

                if invoice_line.currency_id.is_zero(distributed_amount):
                    continue

                onbalance_amounts_by_line[invoice_line] = (
                    distributed_amount,
                    distributed_amount_currency,
                )
                available_income -= abs(distributed_amount)
                available_income_currency -= abs(distributed_amount_currency)
                if invoice_line.currency_id.is_zero(available_income):
                    break

        # Distribute remaining income equally if any gain is made due to exchange rate
        if (
            onbalance_amounts_by_line
            and invoice_lines
            and not invoice_lines[0].company_currency_id.is_zero(available_income)
            and invoice_lines[0].currency_id.is_zero(available_income_currency)
        ):
            count = len(onbalance_amounts_by_line)
            split_amount = available_income / count
            split_amount_currency = available_income_currency / count

            for line, amounts in onbalance_amounts_by_line.items():
                amt, amt_curr = amounts
                onbalance_amounts_by_line[line] = (
                    amt + copysign(split_amount, amt),
                    amt_curr + copysign(split_amount_currency, amt),
                )

        return onbalance_amounts_by_line

    def _create_onbalance_move_lines(
        self,
        onbalance_amounts_by_line,
        income_entry,
    ):
        """
        Create on-balance move lines based on prorated distribution.

        :param onbalance_amounts_by_line: Dict of (amount, amount_currency)
               by invoice line
        :param income_entry: The income journal entry
        """
        # Prepare line creation
        total_distributed_amount = 0.0
        total_distributed_amount_currency = 0.0
        lines_to_create = defaultdict(
            lambda: {
                "move_id": income_entry.id,
                "is_off_balance_generated": True,
                "name": "Off-Balance Adjustment",
                "off_balance_line_ids": [],
                "debit": 0.0,
                "credit": 0.0,
                "amount_currency": 0.0,
            }
        )

        # Create prorated lines for each account/product combination
        for (
            invoice_line,
            distributed_amount,
        ) in onbalance_amounts_by_line.items():
            currency = invoice_line.currency_id
            amount = currency.round(abs(distributed_amount[0]))
            key = (
                invoice_line.account_id.on_balance_account_id.id,
                invoice_line.product_id.id or False,
                invoice_line.partner_id.id,
            )
            lines_to_create[key].update(
                {
                    "account_id": key[0],
                    "product_id": key[1],
                    "currency_id": currency.id,
                    "partner_id": invoice_line.partner_id.id,
                }
            )
            if distributed_amount[0] > 0:
                lines_to_create[key]["debit"] += amount
            else:
                lines_to_create[key]["credit"] += amount
            lines_to_create[key]["amount_currency"] += distributed_amount[1]

            lines_to_create[key]["off_balance_line_ids"].append((4, invoice_line.id))
            total_distributed_amount += distributed_amount[0]
            total_distributed_amount_currency += distributed_amount[1]

        # Apply rounding adjustment to the last line
        if lines_to_create:
            total_offbalance_amount = sum(
                am[0] for am in onbalance_amounts_by_line.values()
            )
            current_total = sum(
                v["debit"] - v["credit"] for v in lines_to_create.values()
            )
            rounding_adjustment = currency.round(
                total_offbalance_amount - current_total
            )
            if rounding_adjustment:
                last_line = list(lines_to_create.values())[-1]
                if rounding_adjustment > 0:
                    last_line["debit"] += rounding_adjustment
                else:
                    last_line["credit"] -= rounding_adjustment
                total_distributed_amount += rounding_adjustment

            # Recompute totals from the actual rounded lines_to_create values
            # to ensure the off-balance asset line exactly counterbalances
            # the on-balance lines (avoids cumulative rounding mismatches).
            total_distributed_amount = sum(
                v["debit"] - v["credit"] for v in lines_to_create.values()
            )
            total_distributed_amount_currency = sum(
                v["amount_currency"] for v in lines_to_create.values()
            )

            # Create the on-balance lines
            on_balance_lines = self.with_context(check_move_validity=False).create(
                list(lines_to_create.values())
            )

            # Create the off-balance asset line
            currency = on_balance_lines.mapped("currency_id")
            if len(currency) != 1:
                raise ValueError(
                    _("All created on-balance lines should have the same currency")
                )
            self._create_offbalance_asset_line(
                income_entry,
                currency,
                total_distributed_amount,
                total_distributed_amount_currency,
                on_balance_lines.ids,
            )

    def _create_offbalance_asset_line(
        self, income_entry, currency, amount, amount_currency, on_balance_line_ids
    ):
        """
        Create an account move line reflecting the reconciliation amount
        on the off-balance asset account.

        :param income_entry: The income journal entry
        :param currency: The currency for rounding
        :param amount: The total distributed amount (negative for income)
        :param amount_currency: The total distributed amount in currency
        :param on_balance_line_ids: List of created on-balance line IDs
        """
        self.env["account.move.line"].with_context(check_move_validity=False).create(
            {
                "account_id": income_entry.company_id.off_balance_asset_account_id.id,
                "name": "Off-Balance Adjustment",
                "move_id": income_entry.id,
                "partner_id": income_entry.partner_id.id,
                "balance": currency.round(-amount),  # Negative to balance the credits
                "amount_currency": currency.round(-amount_currency),
                "is_off_balance_generated": True,
                "on_balance_line_ids": [(6, 0, on_balance_line_ids)],
                "currency_id": currency.id,
            }
        )

    def _prepare_exchange_difference_move_vals(
        self, amounts_list, company=None, exchange_date=None, **kwargs
    ):
        """
        Replace the exchange rate diff account with the off balance account
        if the income is off-balance.
        """
        res = super()._prepare_exchange_difference_move_vals(
            amounts_list, company=company, exchange_date=exchange_date, **kwargs
        )

        for i, line in enumerate(self):
            exchange_vals = res["move_values"]["line_ids"][((i + 1) * 2) - 1]
            if line.account_id.is_off_balance:
                exchange_account_id = exchange_vals[2]["account_id"]
                off_balance_exchange_account = self.env["account.account"].search(
                    [("on_balance_account_id", "=", exchange_account_id)], limit=1
                )
                if off_balance_exchange_account:
                    exchange_vals[2]["account_id"] = off_balance_exchange_account.id
                    exchange_vals[2]["is_off_balance_generated"] = True

        return res
