from collections import defaultdict

from odoo import fields, models


class AccountMoveLine(models.Model):
    _inherit = "account.move.line"

    is_off_balance_generated = fields.Boolean(
        help="Technical field used to identify lines generated by the off-balance "
        "reconciliation process.",
    )

    def _search(self, domain, offset=0, limit=None, order=None, access_rights_uid=None):
        if self.env.context.get("filter_off_balance"):
            domain.append(("account_id.is_off_balance", "=", False))
        return super()._search(domain, offset, limit, order, access_rights_uid)

    def _reconcile_post_hook(self, data):
        super()._reconcile_post_hook(data)
        income_off_balance = self.move_id.line_ids.filtered(
            lambda move_line: move_line.account_id.is_off_balance
            and move_line.company_id.off_balance_asset_account_id
        )
        if income_off_balance:
            self._register_off_balance_income()

    def _register_off_balance_income(self):
        """
        When an income is reconciled, we look if it was linked to a donation invoiced
        on the off-balance account. If so, we create the corresponding lines on the
        on-balance account.
        We cover eight possible scenarios:
        1. The income is directly reconciled with an invoice
        2. The income is reconciled with a debit order connected with the invoice
        a. Full reconciliation
        b. Partial reconciliation
        :param self: The reconciled lines
        """
        matched_credit_lines = self.matched_credit_ids.credit_move_id
        # Get only real income lines: it must be a debit line on a banking account
        # (it's not one of the reconciliation lines)
        income_move_lines = (
            matched_credit_lines.move_id.line_ids - matched_credit_lines
        ).filtered(
            lambda line: line.account_type in ["asset_cash", "asset_prepayments"]
        )
        if not income_move_lines:
            return

        income_moves = income_move_lines.move_id
        payment_amount = sum(income_move_lines.mapped("debit"))
        already_generated = income_moves.line_ids.filtered("is_off_balance_generated")
        payment_amount -= sum(already_generated.mapped("credit"))

        debit_move = self.matched_debit_ids.debit_move_id.move_id[0]
        if debit_move.move_type == "out_invoice":
            # Scenario 1: The income is directly reconciled with an invoice
            invoice_lines = debit_move.invoice_line_ids
        else:
            # Scenario 2: The income is reconciled with a debit order
            # We fetch all reconciled lines from both moves and filter invoices
            all_lines = self.move_id.line_ids.full_reconcile_id.reconciled_line_ids
            invoice_lines = all_lines.move_id.filtered(
                lambda m: m.move_type == "out_invoice"
            ).invoice_line_ids

        onbalance_amounts_by_account = defaultdict(dict)
        total_offbalance_amount = 0
        for line in invoice_lines.filtered(
            lambda invoice_line: invoice_line.account_id.on_balance_account_id
        ):
            onbalance_account_product = defaultdict(float)
            on_balance_account = line.account_id.on_balance_account_id
            on_balance_product = line.product_id
            remaining_amount = line.credit
            # b. Deduce the amount already generated
            remaining_amount -= sum(
                already_generated.filtered(
                    lambda line, account=on_balance_account, product=on_balance_product:
                    line.account_id == account and line.product_id == product
                ).mapped("credit")
            )
            onbalance_account_product[on_balance_product.id] += remaining_amount
            onbalance_amounts_by_account[on_balance_account.id] = onbalance_account_product
            total_offbalance_amount += remaining_amount

        # Get the ratio to adjust the amount based on
        # the payment made and the value of each product lines
        # Calculate ratio depending on total amount from the sponsorship
        distribution_ratio = (
            payment_amount / total_offbalance_amount if total_offbalance_amount else 0.0
        )

        # Calculate prorated amount for each off_balance line
        # and create the corresponding on_balance move_line
        lines_to_create = []
        total_distributed_amount = 0.0
        # Get the last income entry (in case of partials)
        income_entry = income_moves[-1:]
        line_template = {
            "move_id": income_entry.id,
            "partner_id": income_entry.partner_id.id,
            "debit": 0.0,
            "is_off_balance_generated": True,
            "name": "Off-Balance Adjustment",
        }
        # Get the currency precision
        currency = income_entry.currency_id
        for (
                on_balance_account_id,
                on_balance_account_product,
        ) in onbalance_amounts_by_account.items():
            for (on_balance_product_id, remaining_amount) in on_balance_account_product.items():

                prorated_amount = remaining_amount * distribution_ratio
                distributed_amount = currency.round(prorated_amount)
                lines_to_create.append(
                    {
                        "account_id": on_balance_account_id,
                        "product_id": on_balance_product_id,
                        "credit": distributed_amount,
                        **line_template,
                    }
                )
                total_distributed_amount += distributed_amount

        if lines_to_create:
            rounding_adjustment = currency.round(
                payment_amount - total_distributed_amount
            )
            lines_to_create[-1]["credit"] += rounding_adjustment
            total_distributed_amount += rounding_adjustment
            self.with_context(check_move_validity=False).create(lines_to_create)

        # Create an account_move_line reflecting
        # the reconciliation amount on account_offbalance_asset
        self.env["account.move.line"].with_context(check_move_validity=False).create(
            {
                "account_id": income_entry.company_id.off_balance_asset_account_id.id,
                "name": "Off-Balance Adjustment",
                "move_id": income_entry.id,
                "partner_id": income_entry.partner_id.id,
                "debit": currency.round(total_distributed_amount),
                "credit": 0.0,
                "is_off_balance_generated": True,
            }
        )
        return True

    def _prepare_exchange_difference_move_vals(
        self, amounts_list, company=None, exchange_date=None, **kwargs
    ):
        """
        Replace the exchange rate diff account with the off balance account
        If the income is off-balance.
        """
        res = super()._prepare_exchange_difference_move_vals(
            amounts_list, company=company, exchange_date=exchange_date, **kwargs
        )
        for i, line in enumerate(self):
            exchange_vals = res["move_values"]["line_ids"][((i + 1) * 2) - 1]
            if line.account_id.is_off_balance:
                exchange_account_id = exchange_vals[2]["account_id"]
                off_balance_exchange_account = self.env["account.account"].search(
                    [("on_balance_account_id", "=", exchange_account_id)], limit=1
                )
                if off_balance_exchange_account:
                    exchange_vals[2]["account_id"] = off_balance_exchange_account.id
                    exchange_vals[2]["is_off_balance_generated"] = True
        return res
